[phases.setup]
nixPkgs = ["...", "python311", "nodejs_22"]

[phases.build]
cmds = ["pip install .", "cd frontend && npm install && npm run build"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT src.app:app"
