[phases.setup]
nixPkgs = ["python311", "nodejs_22"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install --prefix frontend"]

[start]
cmd = "echo 'BUILDING FRONTEND...' && npm run build --prefix frontend && echo 'BUILD COMPLETE' && ls -R frontend/dist && gunicorn --bind 0.0.0.0:$PORT src.app:app"
